### ISSUE TITLE
v1.1.x weirdly generates unspecified sizes

### ISSUE THREAD

**Issue by E-VANCE** [Booreiland/responsive-pics#11]
Hi there,

I just updated to v.1.1.1 (from v1.0.1) and saw a couple of images being falsely generated...?

I am calling Responsive.pics with

`ResponsivePics::get_picture(get_post_thumbnail_id(), 'xs:660 360|c, md:728 400|c, xl:920 480|c')`

and what I am seeing is the following images being generated:

```
<picture>
  <source media="(min-width: 1280px)" srcset="/app/uploads/2020/10/dhk-2019-06_altmaier-355x533-center-center.jpg">
  <source media="(min-width: 768px)" srcset="/app/uploads/2020/10/dhk-2019-06_altmaier-728x400-center-center.jpg">
  <source media="(min-width: 0px)" srcset="/app/uploads/2020/10/dhk-2019-06_altmaier-660x360-center-center.jpg">
  <img src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" alt="">
</picture>
```

The large image renders as **355x533**.

The image itself isn't big enough in order to generate the largest retina-version, its dimensions are **800 × 533 pixel** so the issue seems to be rooted there.

Before (and after downgrading to v.1.0.1) the image renders correctly, meaning there is no modification happening and it just outputs the max-size.

The scheduled actions note

```
'id' => 47887
'quality' => 90
'width' => 355
'height' => 533
'crop' => array ( 0 => 'center', 1 => 'center', )
'ratio' => 1
```

and although the ratio seems correct there is still some processing happening...?

Thanks for looking into this, I'll provide more information as needed, just let me know.

**Comment by Twansparant** [comment]
Thanks for reporting this!
I'll try and reproduce this locally and see what's happening., but it should preserve the ratio and crop the image as large as possible to: **800 x 417 px**

**Comment by E-VANCE** [comment]
Many thanks – download the base image [here](https://we.tl/t-gFTIpixrPQ) for debugging purposes.

**Comment by Twansparant** [comment]
Can you give version [1.1.2]( https://github.com/Booreiland/responsive-pics/releases/tag/1.1.2) a go?
This should fix it (and even preserve the desired height factor of 480/920)!

**Comment by E-VANCE** [comment]
Looking good so far, no unspecified sizes / crops happening...! Thanks for the quick fix 🎉
