### ISSUE TITLE
WebP Support

### ISSUE THREAD

**Issue by craigbarlow** [Booreiland/responsive-pics#13]
Hey,

Been using the plugin for a little while and just wondering if there is a way to get it to work with WebP images, I can't see anything about the plugin itself being able to create the WebP images but could it work with another plugin, maybe something like [WebP Express](https://en-gb.wordpress.org/plugins/webp-express/)

Is WebP support something that you will be adding in the future?

Thanks in advanced

**Comment by Twansparant** [comment]
Hi @craigbarlow,

I can see how this would be beneficial for this plugin!
Right now the plugin itself is not able to create WebP images, we would need a converter like the [WebPConvert](https://github.com/rosell-dk/webp-convert) for that.

We do not have the intention to rely on another wordpress plugin to support a certain feature, so if we want to support this, we need to implement this ourselves. And so far, our plugin did not have any dependencies to any image libraries like [ Imagick](https://github.com/Imagick/imagick) etc. so I wonder how feasible this would be for the average wordpress user.

I'll keep you posted on this.
Thanks!

**Comment by mindfullsilence** [comment]
Hey @Twansparant, if webp format is what's initially uploaded to WordPress via the image library, will the plugin work correctly to resize them in theme files? I'm starting on a new project and am super stoked I found this package :D

**Comment by Twansparant** [comment]
Hi @mindfullsilence, it looks like WebP is supported now since Wordpress 5.8:
https://make.wordpress.org/core/2021/06/07/wordpress-5-8-adds-webp-support/
So I'll have a look tomorrow to see if the resizing works just the same for WebP images.

**Comment by Twansparant** [comment]
I just added WebP support in the latest [1.4.4 release](https://github.com/Booreiland/responsive-pics/releases/tag/1.4.4)!
Let me know if that works for you!
