### ISSUE TITLE
usort() error in PHP 8

### ISSUE THREAD

**Issue by joshuafredrickson** [Booreiland/responsive-pics#17]
**Describe the bug**
Using this plugin with PHP 8 results in the following fatal error:

`usort(): Returning bool from comparison function is deprecated, return an integer less than, equal to, or greater than zero`

Referencing [this line in class-rules.php](https://github.com/Booreiland/responsive-pics/blob/c3653cba5f5c4df2aa83d01c66d0e0e756806b1f/src/class-rules.php#L83).

**To Reproduce**
1. Activate this plugin while using PHP 8
2. Visit front-end
3. See error

**Expected behavior**
No error. 

**Software (please complete the following information):**
  - PHP Version: 8.0.9
 - ResponsivePicture version: 1.3.2

**Comment by Twansparant** [comment]
Hi @joshuafredrickson, thanks for reporting this!
We haven't had the chance yet to test our plugin on a PHP 8+ webserver, but I'll review your PR as soon as possible.
Thanks for your time!
