### ISSUE TITLE
ResponsivePics without an ID

### ISSUE THREAD

**Issue by alexkerber** [Booreiland/responsive-pics#21]
Is it possible to load a static image from your assets folder and not from your media lib? Like `@asset('images/default-thumb.jpg')` or so?

**Comment by Twansparant** [comment]
Hi @alexkerber, no I'm afraid not. This plugin is meant for assets within the WP media library and therefore an attachment ID is required. There are loads of tools available though for resizing/cropping local assets in your compiling flow, depending on which tool you use for that.

**Comment by alexkerber** [comment]
I was afraid of that ... amazing work btw! I will just build a similar component for static files
