### ISSUE TITLE
Force Aspect Ratio

### ISSUE THREAD

**Issue by eballeste** [Booreiland/responsive-pics#3]
**Is your feature request related to a problem? Please describe.**
I was playing around with responsive-pics and noticed that for certain sizes, if the original image is smaller, it will load the original image instead (as noted in the docs). 

**Describe the solution you'd like**
I would love to see an option where aspect ratios are respected. So, if flagged, the library will create the largest possible crop that respects the aspect ratio given and load that instead of the original image where it might break a front-end layout that needs the images to follow a certain aspect ratio. 

Awesome library and awesome site by the way, thanks ✌️.

**Comment by Twansparant** [comment]
Hi thanks for using our library!
Which version are you currently using? Because I thought [this commit ](https://github.com/Booreiland/responsive-pics/commit/047d554df8c03e4fb07f82e4e5c0ceb7033906ad) had already fulfilled your request?
I will have a look when I find some time!

**Comment by eballeste** [comment]
I installed `0.7.2` yesterday. Maybe I'm doing something wrong?

```php
use ResponsivePics as Pics;

...
$profile->pic = Pics::get( $profile_pic, 'xs: 330 264|c, md: 470 376|c, lg: 610 488|c, xl: 840 672|c', true, true);
...
```

where I get the correct aspect ratios for mobile but not for the larger breakpoints.
![Screen Shot 2020-02-15 at 12 28 04 PM](https://user-images.githubusercontent.com/6924108/74592375-b07cc880-4fee-11ea-87b1-4cae8437525e.png)
![Screen Shot 2020-02-15 at 12 28 16 PM](https://user-images.githubusercontent.com/6924108/74592376-b672a980-4fee-11ea-93fa-8d17338d9be6.png)

**Comment by eballeste** [comment]
I tried to test it out using version `1.0.0-beta` but now the theme is broken because it's trying to install the library as a plugin. That kinda blows.

**Comment by Twansparant** [comment]
> I tried to test it out using version `1.0.0-beta` but now the theme is broken because it's trying to install the library as a plugin.

Correct, I need to update the docs when I version 1 is out of beta, because we turned it into a plugin. If you use bedrock, move your composer require to the site’s composer.json and you’re good to go! I would recommend adding it as a muplugin.

**Comment by eballeste** [comment]
Blegh. Part of my attraction to this library was that it was not a plugin. I'm not using bedrock, I have a `/lib` folder in my theme directory where I keep all of the composer installed packages. (I am working on a single site/theme that is part of a wordpress multisite install and I don't want to touch anything related to multisite plugins nor having to network activate it. 

I tried [following these instructions](https://getcomposer.org/doc/faqs/how-do-i-install-a-package-to-a-custom-path-for-my-framework.md) for trying to override the `composer/installers` path:
```json
"extra": {
    "installer-paths": {
      "vendor/responsive-pics": ["booreiland/responsive-pics"]
    }
  }
```
 But regardless, composer is not loading/finding the `ResponsivePics` class.

**Comment by Twansparant** [comment]
> Blegh. Part of my attraction to this library was that it was not a plugin.

I understand, I felt the same but the only way to run the image resizing tasks as a background process (so the server won’t time out) on the server is by using the WP cron or a real cron job and then you basically have to turn it into a plugin.

> I am working on a single site/theme that is part of a wordpress multisite install and I don't want to touch anything related to multisite plugins nor having to network activate it in order for the library to work.

Muplugins are not multisite plugins, all my builds are single sites. MU plugin stands for must use plugins. Sonyou don’t have to manually activate them in the admin.

**Comment by eballeste** [comment]
thanks for the clarification on why it needs to be a plugin. 

i won't be able to use this plugin for reasons specific to this project (it's a multisite install and I'm restricted to working from a single theme with the available plugins (both regular and those in the mu folder). so going to the root of the multisite and using composer to install things outside of the theme folder is out of the question for me.

I'm leaving this issue open because the original cropping issue might still be a thing? I'll definitely revisit this plugin for other projects where I'm not blocked by red tape, thanks for your time!

**Comment by eballeste** [comment]
FYI, I wanted to test out your latest version regardless whether I can use it or not in this project but still got the same uncropped images for larger breakpoints.

**Comment by eballeste** [comment]
I was looking through the code and figured out that the aspect ratio will be enforced only when you specify a factor value instead of an explicit height.

Instead of
```
$profile->pic = Pics::get( $profile_pic, 'xs: 330 264|c, md: 470 376|c, lg: 610 488|c, xl: 840 672|c', true, true);
```
I did:
```
$profile->pic = Pics::get( $profile_pic, 'xs:330/0.8|c, md:470/0.8|c, lg:610/0.8|c, xl:840/0.8|c', true, true);
```

This worked for some but not all images, where i noticed that sometimes the new height is taller than the available height. #4 first compares the heights and makes sure the aspect ratio is enforced based on that check.
