### ISSUE TITLE
Native lazy loading option

### ISSUE THREAD

**Issue by Jensderond** [Booreiland/responsive-pics#30]
**Is your feature request related to a problem? Please describe.**
The option to use native lazy loading

**Describe the solution you'd like**
An option to use `loading="lazy"` instead of using a plugin such as Lazysizes or Lozad.

**Additional context**
It is [widely supported in modern browser](https://caniuse.com/loading-lazy-attr) for images

**Comment by Twansparant** [comment]
Hi Jens,
Thanks for your PR! I had a look at it and it looks good, but I'd rather incorporate this in the existing `lazyload` parameter, with a third optional value `native` (or something like that) next to `true` or `false`.
I'll try to add this feature this week!

**Comment by Twansparant** [comment]
Added in version 1.6.3!
