### ISSUE TITLE
Docs need correction --> Lazyloading & Intrinsic Aspectratio 

### ISSUE THREAD

**Issue by E-VANCE** [Booreiland/responsive-pics#6]
_Great plugin, thanks so much for sharing, very much appreciated...!_

**Describe the bug**
In your [examples section](https://responsive.pics/#examples) regarding lazyloading & intrinsic aspectratio you are stating that one should pass `true` as **3rd** respectively **4th** which isn't correct (any more?) since the `classes`-parameter is on 3rd now and a full call including lazyloading & intrinsic aspectratio should read

`<?= ResponsivePics::get(1, 'xs-12, lg-10, xl-8', '', true, true); ?>`

_(empty class as 3rd)_

Took me a bit to "solve" this, wasn't sure what I was doing wrong 😆

Thanks again!

**Comment by Twansparant** [comment]
You're absolutely right! The docs need revisioning anyway for the upcoming 1.0.0 version, but thanks for catching this one! I have corrected this one right away :)

**Comment by E-VANCE** [comment]
First of all: Thanks & congrats for v.1! Great work.

The docs still carry a faulty passage:

> To enable intrinsic aspect ratio for your responsive picture, pass true as the 4th parameter

`<?= ResponsivePics::get_picture(1, 'xs-12, lg-10, xl-8', true, true); ?>`

Should read:

`<?= ResponsivePics::get_picture(1, 'xs-12, lg-10, xl-8', '', true, true); ?>`

_Tested with v1.0.1_

**Comment by Twansparant** [comment]
> First of all: Thanks & congrats for v.1! Great work.

Thanks, glad you like it!
And also thanks again for your alertness in spotting those typos in the docs!
I corrected it right away
